services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    container_name: morph-keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
    ports:
      - "8080:8080"
    volumes:
      - ./morph-realm.json:/opt/keycloak/data/import/morph-realm.json
    command: start-dev --import-realm --features=token-exchange,admin-fine-grained-authz
