name: Dart (packages)

on:
  push:
    branches: [main, f/plugin, "feat/**"]
  pull_request:
    branches: [main, f/plugin]

jobs:
  morph_dart:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - morph_core
          - morph_oauth2
          - morph_logger
    defaults:
      run:
        working-directory: packages/dart/${{ matrix.package }}
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Install dependencies
        run: dart pub get
      - name: Analyze
        run: dart analyze --fatal-infos
      - name: Test
        run: dart test
